### ISSUE TITLE
Exception when trying to run the app

### ISSUE THREAD

**Issue by GenaBitu** [GoogleChromeLabs/svgomg-twa#2] opened 2019-02-04 16:04 UTC
Hi,
I've tried cloning the repository, changing the manifest overrides and applicationId in `app/build.gradle`, running enable-debug.sh and I get the following exception when trying to run the app:

```java
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: cz.skaut.odyssea.odymaterialy, PID: 16631
                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.customtabs.CustomTabsSession.validateRelationship(int, android.net.Uri, android.os.Bundle)' on a null object reference
                      at android.support.customtabs.TrustedWebUtils.launchAsTrustedWebActivity(TrustedWebUtils.java:91)
                      at android.support.customtabs.trusted.LauncherActivity$TwaCustomTabsServiceConnection.onCustomTabsServiceConnected(LauncherActivity.java:192)
                      at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:44)
                      at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
                      at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6694)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

My device is the Xiaomi Mi A2 Lite, running Android One, Android version 9 with build version `PKQ1.180917.001.V10.0.3.0.PDLMIXM`. I am running Chrome version `72.0.3626.76`, the latest I can get from the Play store

Do you have any idea what could be causing this? I am a relative beginner to Android development, so any help is appreciated.

Thank you

**Comment by GenaBitu** [comment] 2019-02-04 16:05
I get the same result in AVD as well

**Comment by andreban** [comment] 2019-02-05 10:49
This looks like an issue in the Support Library. Would you mind filing a bug report against it using this [template](https://code.google.com/p/chromium/issues/entry?summary=Issue%20Summary&comment=Application%20Version%20(from%20%22Chrome%20Settings%20%3E%20About%20Chrome%22):%20%0DAndroid%20Build%20Number%20(from%20%22Android%20Settings%20%3E%20About%20Phone/Tablet%22):%20%0DDevice:%20%0D%0DSteps%20to%20reproduce:%20%0D%0DObserved%20behavior:%20%0D%0DExpected%20behavior:%20%0D%0DFrequency:%20%0D%3Cnumber%20of%20times%20you%20were%20able%20to%20reproduce%3E%20%0D%0DAdditional%20comments:%20%0D&labels=OS-Android,Cr-UI-Browser-Mobile-CustomTabs).

**Comment by GenaBitu** [comment] 2019-02-05 10:50
Hi, thanks, will do.

**Comment by GenaBitu** [comment] 2019-02-05 10:57
https://bugs.chromium.org/p/chromium/issues/detail?id=928701

**Comment by andreban** [comment] 2019-02-11 08:19
Thanks! Closing the bug here to follow-up on Chromium.

**Closed by andreban** 2019-02-11 08:19 UTC
Labels: bug
