### ISSUE TITLE
PWA : ask users to update chrome version

### ISSUE THREAD

**Issue by navinSing** [GoogleChromeLabs/svgomg-twa#89] opened 2020-01-29 08:12 UTC
Lost of old users(around 25% in my case) are using older version of chrome or not using chrome.
On App start how can i redirect them with a message to update / install chrome on mobile.

**Comment by PEConn** [comment] 2020-01-29 10:25
Hey,

(As some context, svgomg-twa pulls in the [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper) library.)

We already have [this feature](https://github.com/GoogleChrome/android-browser-helper/blob/5f6d124afa28b1693bc2f047f570656a06d057a6/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/ChromeUpdatePrompt.java) for old versions of Chrome. If the user has a version from before Chrome 72, we display a Toast asking them to update to 72 or further (but still continue on to the web page but with the top bar present).

As for telling users without Chrome to install Chrome - we didn't want to use TWAs to push Chrome, so we decided not to show a Toast in that case.

If you want to customise this behaviour, you could have a look at the [twa-custom-launcher](https://github.com/GoogleChrome/android-browser-helper/blob/5a0accde2341108fcc7eb7d0b0e0d7ce45a29962/demos/twa-custom-launcher/src/main/java/com/google/androidbrowserhelper/launchtwa/LaunchTwaActivity.java) demo.

You may also be interested in [this open issue](https://github.com/GoogleChrome/android-browser-helper/issues/15) which would add a WebView fallback in case the user has no supporting browsers installed. There is also a [demo for this](https://github.com/GoogleChrome/android-browser-helper/tree/5a0accde2341108fcc7eb7d0b0e0d7ce45a29962/demos/twa-webview-fallback), though I don't know how production ready that is.

**Comment by andreban** [comment] 2020-01-29 10:30
Adding to what Peter said, the WebView fallback demo shows [how to add your own behaviour ](https://github.com/GoogleChrome/android-browser-helper/blob/5a0accde2341108fcc7eb7d0b0e0d7ce45a29962/demos/twa-webview-fallback/src/main/java/com/google/browser/examples/twawebviewfallback/MyLauncherActivity.java#L25-L32)when a browser that supports TWAs is not available. 

It would be possible to, instead of using a WebView as a fallback, starting your own Activity with your own message for users.

**Comment by andreban** [comment] 2020-02-21 08:33
Closing the issue, as the feature already exists. Please, file a bug on Chromium Bugs if it's not working as intended.

**Closed by andreban** 2020-02-21 08:33 UTC
