### ISSUE TITLE
App crashes with IllegalStateException

### ISSUE THREAD

**Issue by Jcholerton** [GoogleChromeLabs/svgomg-twa#42] opened 2019-08-08 17:10 UTC
Hi,

We're getting a small number of crashes from various devices with the following stack trace:

```
java.lang.IllegalStateException: 
  at android.support.customtabs.trusted.TwaLauncher.launchWhenSessionEstablished (TwaLauncher.java:176)
  at android.support.customtabs.trusted.TwaLauncher.lambda$launchTwa$0$TwaLauncher (TwaLauncher.java:158)
  at android.support.customtabs.trusted.-$$Lambda$TwaLauncher$0c_zkUHgDllmcAlOM3gechJInp0.run (Unknown Source:8)
  at android.support.customtabs.trusted.TwaLauncher$TwaCustomTabsServiceConnection.onCustomTabsServiceConnected (TwaLauncher.java:226)
  at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected (CustomTabsServiceConnection.java:44)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1839)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1871)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```

Seems to be something going wrong when trying to establish the session. Is this a known issue?

Thanks

**Comment by andreban** [comment] 2019-08-08 17:15
Can you confirm the version of the Support Library being used? The latest version is `91b4a1270b`.

**Comment by Jcholerton** [comment] 2019-08-12 11:25
We were using an earlier version but updated to 91b4a1270b on Friday. Over the weekend we've still seen some instances of the same error.

**Comment by andreban** [comment] 2019-08-12 11:31
Can you confirm those errors are happening on the latest version of your app (the one that uses the latest version of the library).

**Comment by Jcholerton** [comment] 2019-08-12 11:39
Yes, the errors are happening on the latest version.

**Comment by andreban** [comment] 2019-08-12 11:42
Thanks for confirming. Can you file a bug against the library using [this template](https://code.google.com/p/chromium/issues/entry?summary=Issue%20Summary&comment=Application%20Version%20(from%20%22Chrome%20Settings%20%3E%20About%20Chrome%22):%20%0DAndroid%20Build%20Number%20(from%20%22Android%20Settings%20%3E%20About%20Phone/Tablet%22):%20%0DDevice:%20%0D%0DSteps%20to%20reproduce:%20%0D%0DObserved%20behavior:%20%0D%0DExpected%20behavior:%20%0D%0DFrequency:%20%0D%3Cnumber%20of%20times%20you%20were%20able%20to%20reproduce%3E%20%0D%0DAdditional%20comments:%20%0D&labels=OS-Android,Cr-UI-Browser-Mobile-CustomTabs)?

**Comment by nirmalraghavan** [comment] 2019-09-03 05:56
> Can you confirm the version of the Support Library being used? The latest version is `91b4a1270b`.

How do we find the latest version?
From Google's [documentation](https://developers.google.com/web/updates/2019/02/using-twa), they says to use `7a2c1374a3`. But this didn't work for me. Is there way to find the latest version support library? How we will know when a new version is released?

**Comment by rockeynebhwani** [comment] 2019-09-15 12:28
@andreban - We are using latest library version (91b4a1270b) for our TWA but we are seeing similar errors.

**Comment by rockeynebhwani** [comment] 2019-09-15 12:36
> Yes, the errors are happening on the latest version.

@Jcholerton  - Did you file bug with chromium team as suggested by @andreban ?

**Comment by passiondroid** [comment] 2019-09-16 04:09
Filed a bug - 
https://bugs.chromium.org/p/chromium/issues/detail?id=1004115

**Comment by rockeynebhwani** [comment] 2019-10-07 09:58
See this - https://bugs.chromium.org/p/chromium/issues/detail?id=988346

**Comment by PEConn** [comment] 2019-10-07 10:05
(sorry for the noise!)

@andreban This issue has been fixed on the custom-tabs-client, I think all we need to do is update the version we depend on.

**Comment by andreban** [comment] 2019-10-07 13:05
@rockeynebhwani Could you update to the latest version and let us know if you still see the issue on that?

I have updated `svgomg-twa` to use the latest on #51

**Comment by rockeynebhwani** [comment] 2019-10-07 13:11
@andreban  - I have asked our dev team to upgrade to latest version but currently we are blocked on rolling out our app to more users due to paypal issue (on another thread we talked about) so it may take some time before new users download the app. We don't want to roll out to more customers with known issue with Paypal

**Comment by andreban** [comment] 2020-02-21 08:21
Closing the issue here, in favour of tracking in chromium bugs.

**Closed by andreban** 2020-02-21 08:21 UTC

**Comment by AlexBorsody** [comment] 2020-06-06 20:00
Got a similar error today in the logs, should this be filed in chromium bugs instead?


Huawei HUAWEI Y7 Prime 2018 (HWLDN-Q), 3072MB RAM, Android 8.0
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3303)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3411)
  at android.app.ActivityThread.-wrap12 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1994)
  at android.os.Handler.dispatchMessage (Handler.java:108)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
Caused by: java.lang.IllegalStateException: 
  at android.app.Activity.onCreate (Activity.java:1081)
  at androidx.core.app.ComponentActivity.onCreate (ComponentActivity.java)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:6)
  at androidx.appcompat.app.AppCompatActivity.onCreate (AppCompatActivity.java:42)
  at com.google.androidbrowserhelper.trusted.LauncherActivity.onCreate (LauncherActivity.java)
  at android.app.Activity.performCreate (Activity.java:7383)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1218)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3256)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3411)
  at android.app.ActivityThread.-wrap12 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1994)
  at android.os.Handler.dispatchMessage (Handler.java:108)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
```

**Comment by andreban** [comment] 2020-06-08 09:48
@AlexBorsody filing on https://bugs.chromium.org/ or https://github.com/GoogleChrome/android-browser-helper is best - This repository is a demo app that uses the library.

It's also helpful to attach `AndroidManifest.xml` and `build.gradle`, so we know which parameters are being passed to the LauncherActivity, which support library version is being used, etc. 

This specific error seems to come from the [onCreate](https://github.com/GoogleChrome/android-browser-helper/blob/master/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/LauncherActivity.java#L118), which is really the entry-point for the application and the issue happens on a call to the framework (`super.onCreate()`).

The stack trace doesn't gives a full picture (eg: error message), but I wonder if it's related to this section of code: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/oreo-release/core/java/android/app/Activity.java#986, although we don't request an specific orientation (we to target Android10 and use a transparent Activity).

**Comment by AlexBorsody** [comment] 2020-06-08 14:01
OK I think I see what it is, it would be cool if there was a way we could fix the orientation to portrait. The "added from home screen" version respects the orientation set in the website's manifest.json so portrait is locked in that version but not in the TWA build.

**Comment by andreban** [comment] 2020-06-08 14:08
+1 to that. The Feature Request is being tracked in this issue: http://crbug.com/989606 It'd be great if you could chime in and add any details you can on what you are building.
