### ISSUE TITLE
Push notifications open in new a Chrome tab instead of TWA after Chrome 80

### ISSUE THREAD

**Issue by bschlie** [GoogleChromeLabs/svgomg-twa#94] opened 2020-02-13 13:39 UTC
Hi.

I'm working on a TWA and until recently I have been able to receive FCM notifications and open the TWA by pressing them.
But now, instead of open the link in the TWA, the page is opened in a new chrome tab . I suspect the change is caused by the latest Chrome update 80.0.3987.87. 
When using Chrome version 79.0.3945.136 it works as expected.

Debugging the service worker in the PWA shows that 

"event.waitUntil(self.clients.openWindow(url));"

is called, and logging the service worker clients reveals that the TWA is registered as a client.

The Android Manifest contains the intent-filter "android.intent.action.VIEW" similar to the SVGOMG-TWA.

Adding breakpoints to TrustedWebActivityService shows that onCreate is never called in Chrome 80 either, however this method is called when downgrading to Chrome 79.
 
Am I missing something?

**Comment by naveedahmed1** [comment] 2020-02-13 22:51
I am also having the same issue, with latest version of `svgomg-twa` on Chrome 80.x

**Comment by naveedahmed1** [comment] 2020-02-13 23:09
I'm also not sure if this should be reported here or it should be reported directly to Chrome team.

**Comment by andreban** [comment] 2020-02-14 08:19
@naveedahmed1 The team developing the feature in Chrome and the support library do check the issues on svgomg-twa as well (and we also talk to each other). Having said that, the best place to file this bug is indeed in bugs.chromium.org.  This is the right component: https://bugs.chromium.org/p/chromium/issues/list?q=component%3AUI%3EBrowser%3EMobile%3ETrustedWebActivities&can=2

**Comment by naveedahmed1** [comment] 2020-02-14 10:05
Thank you so much @andreban, I have filed the issue there https://bugs.chromium.org/p/chromium/issues/detail?id=1052288&can=2&q=component%3AUI%3EBrowser%3EMobile%3ETrustedWebActivities

**Comment by andreban** [comment] 2020-02-21 08:34
Closing the issue here, in favour of tracking it in Chromium Bugs

**Closed by andreban** 2020-02-21 08:34 UTC

**Comment by jahooma** [comment] 2020-02-23 23:04
I hope this can be fixed soon!

**Comment by naveedahmed1** [comment] 2020-04-28 02:39
I think the issue isn't fully fixed, I posted a comment here https://bugs.chromium.org/p/chromium/issues/detail?id=1052288&can=2&q=component%3AUI%3EBrowser%3EMobile%3ETrustedWebActivities

But I am not sure if its still being tracked or not, since the issue is already marked as closed.

@andreban can you please take a look, and if required please reopen the issues?

**Comment by andreban** [comment] 2020-04-28 08:50
@naveedahmed1 Your comment looks like a slightly different issue where instead of re-using an instance of the app, another is created. Would you mind filing a separate bug? It'd be great if you could record a video of the issue. (PS: I've been working on a [thing][1] that may [make recording stuff like that easier])

[1]: https://bandarra.me/projects/webusb/screenrecord.html
[2]: https://twitter.com/andreban/status/1248344020167921667

**Comment by naveedahmed1** [comment] 2020-04-28 17:03
Thanks @andreban I have filed a new issue here https://bugs.chromium.org/p/chromium/issues/detail?id=1076039 , can you please assign the appropriate category so that it reaches to the TWA team.

I have also attached the video. Your tool was super convenient and useful, great job 👍

I found few posts saying that Video recording is availabe in Android 10 but its behind a flag.

**Comment by PEConn** [comment] 2020-05-13 12:37
Hey @naveedahmed1, I'm unable to reproduce - do you mind sharing an `adb logcat` of what's going on? (Do have a look through it before sharing, it may contain personal information.)

Also, you're creating your TWA by using bubblewrap right?

**Comment by naveedahmed1** [comment] 2020-05-13 20:55
Thank you for your reply @PEConn the current version is based on https://github.com/GoogleChromeLabs/svgomg-twa

I just deployed a new version with App Icon Shortcuts, this version is based on bubblewrap, but I think it will take some time before it goes live.

I will try adb logcat, btw one of your team member was able to reproduce the issue as reported here https://bugs.chromium.org/p/chromium/issues/detail?id=1076039

**Comment by PEConn** [comment] 2020-05-19 15:00
Sorry for the delay, I've been quite busy - is there any chance you've given `bubblewrap` a go, and if so, does the issue still happen?

**Comment by naveedahmed1** [comment] 2020-05-19 15:45
Thanks @PEConn for your reply. Yes the current version of our app is based on bubble wrap but issue still persists.

**Comment by PEConn** [comment] 2020-05-20 13:18
Looking at the [video you provided][1], at about 4 seconds, you open the notification drawer and show two notifications.

Notification #1 starting with "Email chat support specialist" which is branded with the icon of your app and notification #2 starting with "Experienced C# developer", which is branded with the Chrome icon.

Are these both web push notifications? I'm confused as to how one of them is displayed by Chrome and the other is displayed by your app. Which one did you press on?

[1]: https://00e9e64bac154503e8a4ddba96ebd008a7c227bdc836baf884-apidata.googleusercontent.com/download/storage/v1/b/monorail-prod.appspot.com/o/16%2Fattachments%2F714eee9a-35ab-46d0-8423-4d8593bd5858?qk=AD5uMEs6W_OUp5NwKslrtNMCJnvB2fHUbYVzkjiwtUha2m6e9zvKxq_aA0_44l0eE30ewdFAFQm_v1HJYipujO2OnGSnW1raA4ry-B9znBYBG-gcw1_7qoVZCtFTy5wDwDYft6OAb31iwNewrJekF9ZxgJ8Pfwkg_kmBfLavt6wNoLwq71SQ4AvtNUXY_xwmkcZduLlkALnLRDPKhrEllnx0zmA2d4IK1qIiavp8T8jOhp8-vvq8AobrSkVSuh6GelRIlsBo1On7LIwXG3XLpi9vGICxFZDeOp6W7rQkkdPCEyWuWaNW6MnWoIeTJsk9khQnkQQJ3izyQMFmGfePTc3UOPUsWGqaqkxlp0H4vbuRbQO7fFPl5b2KfVKTEyv7KK1tXNYJ_IdgRHqmty1Yb01xgUIYVlGHRlrxdtD2m02MkGFdtTciDAjI6DeBXCqs_g-9GxOoh4CfR1H8WIM-vpXbUkTTlc9-QSf0RYLU5nrMno1osJg9fVuOKL_wsR1jXhDW1cvi8tCGEIx87sKQw3cUQSdCN-bs0r-RWrsRpYlf--PwSatAxq6Irc1U1FJOQhIzxB9TIjkgsxrKMLm_V8v3CHr0o20aeAjnRZwpwnBhO3upmGq8DIfXycuHS4JxfhVI0Mr3TC35-F14CG9YiSRZd3GQ5tbbCI5eBSDo40LwW1PY5MMWzsj_LQkt8LiqPLS6b-ivZGWE5rC_mbv8ec0Ozt01fTHmaKF1cCbUcrtwYihl4dIXAR79Bzfnf890Qsprfgqht9L-cYTnIdTpL94sZJF_TxdMfosyJHqOAD4ReVS-stftf0CU3Wu1pfHXoH_SgrJSoYCPSylB75O03-21KRhHHn-CIqn3AMFe8UugIDIp87xyMTNsLN0QWoe4ELOB-GCSNVE3

**Comment by naveedahmed1** [comment] 2020-05-20 14:43
I'm not sure why it's showing the icon with one notification and not with other but both are web notifications.

I just tested it again with latest version of the app which is based on Bubblewrap, tapped on the notifications (branded) and the issue still exists.

**Comment by PEConn** [comment] 2020-06-03 14:57
Is there any chance you could add some test page to your website that would display a notification without requiring the user to be signed in? Could you also attach and up-to-date APK? (I'm using test emulators that don't have the Play Store installed.)

**Comment by naveedahmed1** [comment] 2020-06-03 15:35
Here's the apk [app-release.zip](https://github.com/GoogleChromeLabs/svgomg-twa/files/4724398/app-release.zip)

If you have notifications enabled for the app (the bell icon shown on bottom left is blue), you should be able to receive non personalized notifications about new job postings.

**Comment by PEConn** [comment] 2020-06-04 08:02
Hey,

Unfortunately I'm finding it hard to get to a place where I can test notifications with your app. (As an aside, the app you sent me was an `aab`, which needs to be converted to an `apk` before it is installed. Converting an `aab` to an `apk` requires resigning, so I can't do it otherwise digital asset links will break. No worries about this though, I downloaded on a different device from the Play Store.)

1. The TWA launches to a log in page - I can't see any way of getting around it without signing in.
2. Once signed in, I can't click on the notification icon because it is covered by a "please verify your email" prompt.
3. Once my email is verified I can't go any further in the app without uploading a Resume.
4. At this point I gave up.

**Comment by naveedahmed1** [comment] 2020-06-04 10:08
I'm really sorry for the inconvenience. Can you please try it one more time, it shouldn't ask you to create resume now.

**Comment by PEConn** [comment] 2020-06-04 10:26
Ah cool, I've enabled notifications now, just have to wait to get one! I'm getting an odd issue where I click on the notification icon in the bottom left, it turns blue then if I refresh the page (pull down from the top) it turns yellow again.

I must say your app is very nicely designed - it's very fluid to navigate around.

**Comment by naveedahmed1** [comment] 2020-06-04 11:17
Glad to know it finally works on your device.

Have you received any notifications?

If you relaunch the app whats the default color of the notifications icon? If its blue this means that the notifications are enabled, if its yellow, this means that there's some issue.

If its Yellow, tap once, close and then launch again and see if the bell icon is blue or still same.

> I must say your app is very nicely designed - it's very fluid to navigate around.

Thank you so much for the kind words :)

**Comment by PEConn** [comment] 2020-06-04 11:32
Unfortunately no notifications yet.

You can see a video of what's happening [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1076039#c7) (GitHub doesn't support mp4 attachments.)

**Comment by naveedahmed1** [comment] 2020-06-04 11:38
Oh that's strange, it seems that the Push Registration is failing on your device, whereas its working fine on my device. Let me check few things on my side.

**Comment by naveedahmed1** [comment] 2020-06-04 13:03
On one of the devices I was able to reproduce the behavior you mentioned above and when i check the console log it says `Unable to subscribe to push. DOMException: Registration failed - push service error`. And its happening with Chrome only, when I test it with other browser e.g. Firefox on same device, it works just fine.

Seems some issue with Chrome, I have verified it with two other push notifications demo links:
https://gauntface.github.io/simple-push-demo/

https://fcm-demo-mtbqzgkaoz.now.sh/

I get same error on these links as well. Can you please test above links on that particular devices on which you installed Mustakbil app and see if you are able to enable push notifications for these websites?

**Comment by naveedahmed1** [comment] 2020-06-24 11:48
@PEConn just wanted to check if you were able to reproduce the issue?
