### ISSUE TITLE
Android TV app 

### ISSUE THREAD

**Issue by shrw** [GoogleChromeLabs/svgomg-twa#111] opened 2020-10-23 23:42 UTC
I was trying to run the app published(created with this library) on play store on my Android TV 

I/OpenGLRenderer: Davey! duration=1588ms; Flags=0, IntendedVsync=85294375864, Vsync=85294375864, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=85300204600, AnimationStart=85300236800, PerformTraversalsStart=85300260700, DrawStart=85300629400, SyncQueued=85300648400, SyncStart=85300758100, IssueDrawCommandsStart=85300807700, SwapBuffers=85301335900, FrameCompleted=86882937700, DequeueBufferDuration=208000, QueueBufferDuration=409000, 
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5470549
D/TWALauncherActivity: Using URL from Intent (https://xx/).
D/TWAProviderPicker: Found no TWA providers, using first browser: null
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@2076314
D/EGL_emulation: eglMakeCurrent: 0xea644960: ver 2 0 (tinfo 0xea6c1550)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@d15ce5f
D/TWALauncherActivity: Using URL from Intent (https://xx/).
D/TWAProviderPicker: Found no TWA providers, using first browser: null
D/EGL_emulation: eglMakeCurrent: 0xea644960: ver 2 0 (tinfo 0xea6c1550)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@2adfb62
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5de11e5
D/TWALauncherActivity: Using URL from Intent (https://xx/).
D/TWAProviderPicker: Found no TWA providers, using first browser: null
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1b55ae0
D/EGL_emulation: eglMakeCurrent: 0xea644960: ver 2 0 (tinfo 0xea6c1550)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@40ec95b

**Comment by andreban** [comment] 2020-10-24 06:49
This repository is deprecated. This is also duplicate of #91 

Trusted Web Activity is not supported on Android TV. There's an issue open here: https://bugs.chromium.org/p/chromium/issues/detail?id=1054737 and I'd recommend starring the issue there to let the team have a better idea of the demand for support.

**Closed as completed by andreban** 2020-10-24 06:49 UTC
